# Generated by Django 4.0.4 on 2022-05-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_rename_is_admin_user_is_staff_studyroom_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
