# Generated by Django 4.0.4 on 2022-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='studyRoom',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='StudyRoom',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
