# Generated by Django 4.0.5 on 2022-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
