# Generated by Django 4.0.4 on 2022-05-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyroom', '0002_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_studyrooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyroom',
            name='users',
            field=models.ManyToManyField(related_name='studyrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
