# Generated by Django 4.0.4 on 2022-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0003_studyroom_mentor_studyroom_users_tag_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
