# Generated by Django 4.0.4 on 2022-05-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studyroom',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyroom',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyroom',
            name='study_type',
            field=models.CharField(choices=[('study', '스터디'), ('project', '프로젝트')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyroom',
            name='user_num_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='weekly_plan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='weekly_plan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_image',
            field=models.ImageField(default=None, upload_to='tag_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyroom',
            name='technology_stack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studyroom.technologystack'),
            preserve_default=False,
        ),
    ]
