# Generated by Django 4.0.4 on 2022-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0006_technologystack_remove_posts_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='studyroom_type',
            field=models.CharField(choices=[('study', '스터디'), ('project', '프로젝트')], default='study', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='study_type',
            field=models.CharField(choices=[('contactless', '비대면'), ('contact', '대면')], default='contact', max_length=20),
        ),
    ]
