# Generated by Django 4.0.4 on 2022-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0008_studyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyschedule',
            name='content',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
