# Generated by Django 4.0.4 on 2022-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0010_studyschedule_unique_study_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyschedule',
            name='title',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
