# Generated by Django 4.0.5 on 2022-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0011_studyschedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
